controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

teachers:
    path: /teachers
    controller: App\Controller\TeacherController::getTeachersList
